### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by blikr** [hexo-theme-Acrylic/Hexo-Theme-Acrylic#22]
大佬，启动时候报错：
Unhandled rejection TypeError: /Users/beiwangshan/Desktop/hexo/myblog/themes/Acrylic/layout/includes/widget/index.pug:32
    30|         !=partial('includes/widget/card_tags', {}, {cache: true})
    31|         hr
  > 32|         !=partial('includes/widget/card_webinfo', {}, {cache: true})

/Users/beiwangshan/Desktop/hexo/myblog/themes/Acrylic/layout/includes/widget/card_webinfo.pug:18
    16|           i.item-icon.fas.fa-font
    17|             .item-name=_p('aside.card_webinfo.site_wordcount') + " :"
  > 18|           .item-count=totalcount(site)
    19| 
    20| 

totalcount is not a function
    at eval (eval at wrap (/Users/beiwangshan/Desktop/hexo/myblog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:54:57)
    at template (eval at wrap (/Users/beiwangshan/Desktop/hexo/myblog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:58:7)
    at _View._compiledSync (/Users/beiwangshan/Desktop/hexo/myblog/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/Users/beiwangshan/Desktop/hexo/myblog/node_modules/hexo/lib/theme/view.js:59:25)
    at /Users/beiwangshan/Desktop/hexo/myblog/node_modules/hexo/lib/plugins/helper/partial.js:31:52
    at Cache.apply (/Users/beiwangshan/Desktop/hexo/myblog/node_modules/hexo-util/lib/cache.js:27:46)
    at Object.fragmentCache (/Users/beiwangshan/Desktop/hexo/myblog/node_modules/hexo/lib/plugins/helper/fragment_cache.js:11:34)
    at Object.partial (/Users/beiwangshan/Desktop/hexo/myblog/node_modules/hexo/lib/plugins/helper/partial.js:31:17)
    at eval (eval at wrap (/Users/beiwangshan/Desktop/hexo/myblog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2276:46)
    at template (eval at wrap (/Users/beiwangshan/Desktop/hexo/myblog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6488:7)
    at _View._compiled (/Users/beiwangshan/Desktop/hexo/myblog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/beiwangshan/Desktop/hexo/myblog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/beiwangshan/Desktop/hexo/myblog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/beiwangshan/Desktop/hexo/myblog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/beiwangshan/Desktop/hexo/myblog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/beiwangshan/Desktop/hexo/myblog/node_modules/hexo/lib/hexo/router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

看了https://acrylic.zhheo.com/posts/55021/ 文章，里面应该有个source文件，但是无法下载，网盘无法游客登录

**Comment by rootlexblog** [comment]
您好，出现此问题是因为您未安装字数统计插件，您可以在根目录下运行一下指令来安装
`npm install hexo-wordcount --save`

**Comment by timigomen** [comment]
此问题我会在1周内修复，我们目前是默认开启，导致报错
