### ISSUE TITLE
hexo generate编译报错

### ISSUE THREAD

**Issue by spldmanager** [hexo-theme-Acrylic/Hexo-Theme-Acrylic#69]
报错日志如下，不知道是什么问题

```
TypeError: /home/coder/project/myblogger2/themes/Acrylic/layout/tag.pug:9
    7|       !=pagecloud({source: site.tags})
    8|     #recent-posts(class="recent-posts category_ui")
  > 9|       +articleSort(page.posts)
    10|       include includes/part/pagination.pug

pug_mixins.articleSort is not a function
    at eval (eval at wrap (/home/coder/project/myblogger2/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2001:26)
    at template (eval at wrap (/home/coder/project/myblogger2/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:3073:7)
    at _View._compiled (/home/coder/project/myblogger2/node_modules/hexo/dist/theme/view.js:125:67)
    at _View.render (/home/coder/project/myblogger2/node_modules/hexo/dist/theme/view.js:50:21)
    at /home/coder/project/myblogger2/node_modules/hexo/dist/hexo/index.js:58:29
    at tryCatcher (/home/coder/project/myblogger2/node_modules/bluebird/js/release/util.js:16:23)
    at /home/coder/project/myblogger2/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/coder/project/myblogger2/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:547:12)
    at resume_ (node:internal/streams/readable:1048:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
INFO  Generated: zhheo/random.js
```

**Comment by Qxiaoqi** [comment]
https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic/blob/dev/layout/tag.pug#L4

这行改成下面这个，include 错文件了
```pug
include ./includes/mixins/article-sort.pug
```
